/*
  This class has been generated by the Code Generator
*/

package com.ekemait.charting;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class Chart extends ChartBase
{
    public Chart()
    {
        this((BusObjectConfig)null);
    }

    public Chart(BusObjectConfig config)
    {
        super(config);
    }

    public static com.ekemait.charting.Chart getGanttChart()
    {
    	int aa = 1;
    	int bb = aa;
        // TODO implement body
        return null;
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
